apiVersion: v1
entries:
  mumble:
  - apiVersion: v2
    appVersion: v1.5.735-3
    created: "2025-11-03T00:26:53.134701+01:00"
    description: A Helm chart for providing mumble server to kubernetes
    digest: fc93af095dcbbc79f77bfd9990726363566f0177650036f96dceafa7f5add09d
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Icons_mumble.svg/600px-Icons_mumble.svg.png
    keywords:
    - mumble
    - voip
    name: mumble
    sources:
    - https://github.com/mumble-voip/mumble-docker
    type: application
    urls:
    - mumble-0.9.2.tgz
    version: 0.9.2
  - apiVersion: v2
    appVersion: v1.5.735-3
    created: "2025-11-03T00:26:53.134503+01:00"
    description: A Helm chart for providing mumble server to kubernetes
    digest: da50982601f4cab6005b090d25d56628315d6967717ba1de1e33cffdf458e8ef
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Icons_mumble.svg/600px-Icons_mumble.svg.png
    keywords:
    - mumble
    - voip
    name: mumble
    sources:
    - https://github.com/mumble-voip/mumble-docker
    type: application
    urls:
    - mumble-0.9.1.tgz
    version: 0.9.1
  - apiVersion: v2
    appVersion: v1.5.735-3
    created: "2025-11-03T00:26:53.134288+01:00"
    description: A Helm chart for providing mumble server to kubernetes
    digest: 75427f931f2be862fbcb4e45c175ab916885bbc70e462d429028a1e4cb186e20
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Icons_mumble.svg/600px-Icons_mumble.svg.png
    keywords:
    - mumble
    - voip
    name: mumble
    sources:
    - https://github.com/mumble-voip/mumble-docker
    type: application
    urls:
    - mumble-0.9.0.tgz
    version: 0.9.0
  snipeit:
  - apiVersion: v2
    appVersion: 8.3.4
    created: "2025-11-03T00:26:53.176147+01:00"
    description: A Helm chart for providing snipe-it to kubernetes
    digest: a37e8c3c5b2136acea0caf694c182da804e9f110c125beff53ce426d557058df
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-2.0.5.tgz
    version: 2.0.5
  - apiVersion: v2
    appVersion: 8.3.4
    created: "2025-11-03T00:26:53.175856+01:00"
    description: A Helm chart for providing snipe-it to kubernetes
    digest: bbda68fa2c4225a5f758bc1f1fdb32cc4e459ae0dce7794f3d13c1f6aef4dd9e
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-2.0.4.tgz
    version: 2.0.4
  - apiVersion: v2
    appVersion: 8.3.4
    created: "2025-11-03T00:26:53.175555+01:00"
    description: A Helm chart for providing snipe-it to kubernetes
    digest: befacf511e7d9800e00e2044e1db7d0e1481c6e1be3127fe313ef9447cf00bdc
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-2.0.3.tgz
    version: 2.0.3
  - apiVersion: v2
    appVersion: 8.3.4
    created: "2025-11-03T00:26:53.173232+01:00"
    description: A Helm chart for providing snipe-it to kubernetes
    digest: 067b77ac85e22813c70f130b1d53c2073a9fc82cc3e26106d54a24a1c036974d
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-2.0.2.tgz
    version: 2.0.2
  - apiVersion: v2
    appVersion: 8.3.4
    created: "2025-11-03T00:26:53.170669+01:00"
    description: A Helm chart for providing snipe-it to kubernetes
    digest: edc2dc561263e43b690899e16475819e3e7cd11eb38b251953789227c8df10b7
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v2
    appVersion: 8.3.4
    created: "2025-11-03T00:26:53.16833+01:00"
    description: A Helm chart for providing snipe-it to kubernetes
    digest: cafbfdeea991f7be026d16c3ab1a736323bbbbd6488956185b05852bb5dd6a35
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    appVersion: 8.2.1
    created: "2025-11-03T00:26:53.144382+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.3
    description: A Helm chart for providing snipe-it to kubernetes
    digest: 2d6bc59f9dfcda50cbda81292b213de15194db3882512e6f5a7eb863c297b5a3
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.10.tgz
    version: 1.2.10
  - apiVersion: v2
    appVersion: 8.2.0
    created: "2025-11-03T00:26:53.165632+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.3
    description: A Helm chart for providing snipe-it to kubernetes
    digest: 9f8bd32e77ce1d3a842cf357cd498fe11b870b88ca1b6d0ad25b976d3e9a0202
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.9.tgz
    version: 1.2.9
  - apiVersion: v2
    appVersion: 8.2.0
    created: "2025-11-03T00:26:53.163331+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.3
    description: A Helm chart for providing snipe-it to kubernetes
    digest: 846ab26adb35e27c44a84e3c3d4fcb271eabc0802840e5dfee0141ea1bf4fae9
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.8.tgz
    version: 1.2.8
  - apiVersion: v2
    appVersion: 8.2.0
    created: "2025-11-03T00:26:53.160727+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.3
    description: A Helm chart for providing snipe-it to kubernetes
    digest: 00fd43d2d9bc7f09adb3add7fd77de9ebe736e898eb77b022bc4e9d357ed72b2
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.7.tgz
    version: 1.2.7
  - apiVersion: v2
    appVersion: 8.1.18
    created: "2025-11-03T00:26:53.158316+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.1
    description: A Helm chart for providing snipe-it to kubernetes
    digest: 2fff2f481915acf5ca142d8d0d921744ca9635e6cfa425f8a05fc43f34397d7d
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.6.tgz
    version: 1.2.6
  - apiVersion: v2
    appVersion: 8.1.17
    created: "2025-11-03T00:26:53.155576+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.1
    description: A Helm chart for providing snipe-it to kubernetes
    digest: 709a1319559bb9831d456279b2157ee9435bff10bbd6aac1037a2f10dbe1a301
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.5.tgz
    version: 1.2.5
  - apiVersion: v2
    appVersion: 8.1.17
    created: "2025-11-03T00:26:53.152995+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.1
    description: A Helm chart for providing snipe-it to kubernetes
    digest: 3e9949f2cc91daaea650e932b579c927889ebe34affe29f4ac4302fc79c9cfda
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.4.tgz
    version: 1.2.4
  - apiVersion: v2
    appVersion: 8.1.17
    created: "2025-11-03T00:26:53.150137+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.1
    description: A Helm chart for providing snipe-it to kubernetes
    digest: adb9ece40c2ab420e09d8c08bec84e091b552eb752b2a2702f3c4ae8674f65f2
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.3.tgz
    version: 1.2.3
  - apiVersion: v2
    appVersion: 8.1.17
    created: "2025-11-03T00:26:53.147446+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.1
    description: A Helm chart for providing snipe-it to kubernetes
    digest: 2884d043e9d225856ae1416c47a31e451bce9bb07f8ad0a183fdf6105d82d9e1
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.2.tgz
    version: 1.2.2
  - apiVersion: v2
    appVersion: 8.1.16
    created: "2025-11-03T00:26:53.14148+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 20.5.9
    description: A Helm chart for providing snipe-it to kubernetes
    digest: e1e3f4cdabd6fb68ccb27f409c901cb4f8a71ce181bee13d453f648b47b8a8e4
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 8.1.16
    created: "2025-11-03T00:26:53.138211+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 20.5.9
    description: A Helm chart for providing snipe-it to kubernetes
    digest: c44fe6e150d3f1edf85a2d02e0106bcc676d6ef0722b05c47c93d0721aeb76b5
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true
    keywords:
    - snipeit
    - inventory
    - asset management
    name: snipeit
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    - https://github.com/snipe/snipe-it
    type: application
    urls:
    - snipeit-1.2.0.tgz
    version: 1.2.0
  teamspeak:
  - apiVersion: v2
    appVersion: 3.13.7
    created: "2025-11-03T00:26:53.178515+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.3
    description: A Helm chart for providing teamspeak server to kubernetes
    digest: 67e5cf0e0efd59b00acffc9581f27c5e05329e95222f54f04f0219025e298ca2
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://upload.wikimedia.org/wikipedia/commons/e/ec/TeamSpeak_logo_renovado.png
    keywords:
    - teamspeak
    - voip
    name: teamspeak
    sources:
    - https://hub.docker.com/_/teamspeak/
    type: application
    urls:
    - teamspeak-0.9.10.tgz
    version: 0.9.10
  - apiVersion: v2
    appVersion: 3.13.7
    created: "2025-11-03T00:26:53.187451+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.1
    description: A Helm chart for providing teamspeak server to kubernetes
    digest: 84c73828a8c383553b39f01b36d4b26ff2d722911054dd6d5365b010f838c692
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://upload.wikimedia.org/wikipedia/commons/e/ec/TeamSpeak_logo_renovado.png
    keywords:
    - teamspeak
    - voip
    name: teamspeak
    sources:
    - https://hub.docker.com/_/teamspeak/
    type: application
    urls:
    - teamspeak-0.9.9.tgz
    version: 0.9.9
  - apiVersion: v2
    appVersion: 3.13.7
    created: "2025-11-03T00:26:53.185365+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 21.0.1
    description: A Helm chart for providing teamspeak server to kubernetes
    digest: dbcc2cc9dbfbe5ff7ec32bd3e8e6df8a048cf4e6a45f024897eda23a2b154607
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://upload.wikimedia.org/wikipedia/commons/e/ec/TeamSpeak_logo_renovado.png
    keywords:
    - teamspeak
    - voip
    name: teamspeak
    sources:
    - https://hub.docker.com/_/teamspeak/
    type: application
    urls:
    - teamspeak-0.9.8.tgz
    version: 0.9.8
  - apiVersion: v2
    appVersion: 3.13.7
    created: "2025-11-03T00:26:53.183033+01:00"
    dependencies:
    - name: mariadb
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 20.5.9
    description: A Helm chart for providing teamspeak server to kubernetes
    digest: edf82e0903b948fb72797e70c85c440b66c28f92c9081dfb71396f283b3affe7
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://upload.wikimedia.org/wikipedia/commons/e/ec/TeamSpeak_logo_renovado.png
    keywords:
    - teamspeak
    - voip
    name: teamspeak
    sources:
    - https://hub.docker.com/_/teamspeak/
    type: application
    urls:
    - teamspeak-0.9.7.tgz
    version: 0.9.7
  - apiVersion: v2
    appVersion: 3.13.7
    created: "2025-11-03T00:26:53.18093+01:00"
    dependencies:
    - name: mariadb
      repository: https://charts.bitnami.com/bitnami
      version: 20.5.7
    description: A Helm chart for providing teamspeak server to kubernetes
    digest: 1bc51b248ca23a967e8496bc55eebe9875525acd2bbdceb63a51563f00853b96
    home: https://github.com/Syntax3rror404/helm-charts
    icon: https://upload.wikimedia.org/wikipedia/commons/e/ec/TeamSpeak_logo_renovado.png
    keywords:
    - teamspeak
    - voip
    name: teamspeak
    sources:
    - https://hub.docker.com/_/teamspeak/
    type: application
    urls:
    - teamspeak-0.9.6.tgz
    version: 0.9.6
generated: "2025-11-03T00:26:53.134002+01:00"
